MainApp/MainApp/Models/Chat.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MainApp.Models
{
    public class Chat
    {
        [Key]
        public int Id { get; set; }
        [Column("Master")]
        public string Username { get; set; }
        [Required]
        public string Source { get; set; }
        [Required]
        public string GPT { get; set; }
    }
}

MainApp/MainApp/Models/ChatViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MainApp.Models
{
    public class ChatViewModel
    {
        public List<Message> Messages { get; set; }
        public int ChatId { get; set; }
        public string NewMessageText { get; set; }
        public List<Chat> Chats { get; set; }
        public List<DateTime>? LastTimeMessage { get; set; }
        public bool Success { get; set; }
    }
}

MainApp/MainApp/Controllers/ChatController.cs
using MainApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using System;
using System.Globalization;
using System.Net.Http;
using System.Text;
using System.Text.Json;

namespace MainApp.Controllers
{
    public class ChatController : Controller
    {
        private readonly MyDbContext _context;
        private readonly HttpClient _httpClient;
        const long ConstTicks = 0;
        public ChatController(MyDbContext context)
        {
            _context = context;
            _httpClient = new HttpClient();
        }

        [RedirectIfWrongUser]
        public async Task<IActionResult> Index(int id, bool success = true)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            var model = new ChatViewModel();
            model.ChatId = id;
            model.Messages = _context.Messages.Where(m => m.ChatId == id).ToList();
            model.Chats = _context.Chats.Where(c => c.Username == User.Identity.Name).ToList();
            model.LastTimeMessage = model.Chats.Select(c => _context.Messages.Where(m => m.ChatId == c.Id).OrderBy(m => m.Time).LastOrDefault() != null ? _context.Messages.Where(m => m.ChatId == c.Id).OrderBy(m => m.Time).LastOrDefault().Time : DateTime.MinValue).ToList();
            model.Success = success;
            return View(model);
        }

        [RedirectIfWrongUser]
        [HttpPost]
        public async Task<IActionResult> Send(ChatViewModel chatVM)
        {
            bool chatIsFake = false;
            if (chatVM.ChatId == 0)
            {
                var chat = new Chat() { Username = User.Identity.Name, GPT = "YandexGPT", Source = "Habr" };
                try
                {
                    _context.Add(chat);
                    await _context.SaveChangesAsync();
                    chatVM.ChatId = chat.Id;
                    chatIsFake = true;
                }
                catch(Exception e)
                {
                    if (chat.Id > 0)
                    {
                        _context.Chats.Remove(chat);
                        await _context.SaveChangesAsync();
                    }
                    Console.WriteLine("Ошибка Send при создании фейк чата");
                    return RedirectToAction("Index", "Chat", new { id = chatVM.ChatId, success = false });
                }
            }
            
            var message = new Message();
            message.Text = chatVM.NewMessageText;
            message.By = true;
            message.ChatId = chatVM.ChatId;

            //if (!ModelState.IsValid)
            //{
            //    if(chatIsFake)
            //    {
            //        var fakechat = _context.Chats.FirstOrDefault(c => c.Id == chatVM.ChatId);
            //        if (fakechat != null)
            //        {
            //            _context.Chats.Remove(fakechat);
            //            await _context.SaveChangesAsync();
            //        }
            //    }
            //    Console.WriteLine("Ошибка Send: ModelState Is Invalid");
            //    return RedirectToAction("Index", "Chat", new { id = chatVM.ChatId, success = false });
            //}

            Console.WriteLine("Попытка отправки сообщения");
            Console.WriteLine(await _httpClient.GetAsync("http://gptapi:8080/GPT"));

            var timeBorders = await GetTimeBorders(message);

            var news = _context.HabrNews.Where(n => n.Time >= timeBorders.Item1 && n.Time <= timeBorders.Item2).ToList();
            Console.WriteLine($"Нашлось {news.Count()} новостей за даты: {timeBorders.Item1}-{timeBorders.Item2}");

            if(news.Count == 0)
            {
                if (chatIsFake)
                {
                    var fakechat = _context.Chats.FirstOrDefault(c => c.Id == chatVM.ChatId);
                    if (fakechat != null)
                    {
                        _context.Chats.Remove(fakechat);
                        await _context.SaveChangesAsync();
                    }
                }
                Console.WriteLine("Ошибка Send: не нашлось новостей");
                return RedirectToAction("Index", "Chat", new { id = chatVM.ChatId, success = false });
            }

            var tags = _context.HabrTags.ToList();

            var formattedNews = news.Select(n => $"{n.Id}:{n.Title}," + string.Join(',', tags.Where(t => t.Link == n.Link).Select(t => t.Name))).ToArray();

            var specialIds = await GetSpecialTitles(formattedNews,message);

            if(specialIds.Count > 0)
            {
                if(specialIds.Count > 10)
                    specialIds.RemoveRange(10, specialIds.Count - 10);

                var gptAnswer = new List<string>();

                foreach (var id in specialIds)
                {
                    var specialNews = news.FirstOrDefault(n => n.Id == id.ToString());
                    if(specialNews != null && specialNews.Content?.Length > 40)
                    {
                        var answer = await GetGptSummarize(specialNews.Content, chatVM);
                        gptAnswer.Add($"<a style=\"font-weight: bold;\" href=\"{specialNews.Link}\">{specialNews.Title}</a>\n <div>{answer}</div>");
                    }
                }

                var gptMessage = new Message() { ChatId = message.ChatId, Time = DateTime.Now.ToUniversalTime(), By = false, Text = $"Вот что нашлось за даты {timeBorders.Item1.ToString("dd.MM.yyyy")}-{timeBorders.Item2.ToString("dd.MM.yyyy")}:\n\n" + string.Join("\n\n", gptAnswer) };

                try
                {
                    _context.Add(message);
                    _context.Add(gptMessage);
                    await _context.SaveChangesAsync();
                    chatIsFake = false;
                    var messages = chatVM.Messages;
                    if (messages == null)
                        messages = new List<Message>();
                    messages.Add(message);
                    return RedirectToAction("Index", new { id = message.ChatId });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Text", "Ошибка базы данных: " + ex.Message);
                }
            }
            else
            {
                Console.WriteLine("Ошибка: не удалось извлечь новости");
                if (chatIsFake)
                {
                    var fakechat = _context.Chats.FirstOrDefault(c => c.Id == chatVM.ChatId);
                    if (fakechat != null)
                    {
                        _context.Chats.Remove(fakechat);
                        await _context.SaveChangesAsync();
                    }
                }
                return RedirectToAction("Index", "Chat", new { id = chatVM.ChatId, success = false });
            }

            if (chatIsFake)
            {
                var fakechat = _context.Chats.FirstOrDefault(c => c.Id == chatVM.ChatId);
                if (fakechat != null)
                {
                    _context.Chats.Remove(fakechat);
                    await _context.SaveChangesAsync();
                }
            }
            Console.WriteLine("Ошибка Send: конец метода");
            return RedirectToAction("Index", "Chat", new { id = chatVM.ChatId, success = false });
        }

        public async Task<(DateTime, DateTime)> GetTimeBorders(Message message)
        {
            var responseTimeBorders = await _httpClient.PostAsync("http://gptapi:8080/GPT/GetTimeBorders", new StringContent($"\"{message.Text}\"", Encoding.UTF8, "application/json"));
            var timeBorders = (DateTime.Now.ToUniversalTime().AddDays(-7), DateTime.Now.ToUniversalTime());
            if (responseTimeBorders.IsSuccessStatusCode)
            {
                string responseTimeBordersContent = await responseTimeBorders.Content.ReadAsStringAsync();
                Console.WriteLine($"TimeBorders: {responseTimeBordersContent}");
                var splits = responseTimeBordersContent.Split(' ');
                if (splits.Length == 2)
                {
                    try
                    {
                        DateTime date1 = DateTime.ParseExact(splits[0], "dd.MM.yyyy", CultureInfo.InvariantCulture).ToUniversalTime();
                        DateTime date2 = DateTime.ParseExact(splits[1], "dd.MM.yyyy", CultureInfo.InvariantCulture).ToUniversalTime();
                        if (date1 > date2)
                            timeBorders = (date2, date1);
                        else
                            timeBorders = (date1, date2);
                    }
                    catch (Exception ex) { }
                }
            }
            timeBorders.Item2.AddHours(23).AddMinutes(59).AddSeconds(59);
            return timeBorders;
        }

        public async Task<List<int>> GetSpecialTitles(string[] formattedNews, Message message)
        {
            var specialIds = new List<int>();
            var i = 0;
            while(i < formattedNews.Length)
            {
                var array = new string[Math.Min(10, formattedNews.Length-i)];
                Array.Copy(formattedNews, i, array, 0, array.Length);

                var formattedNewsRequest = $"Просьба: {message.Text}\\nМассив записей:\\n" + string.Join("\\n", array);
                formattedNewsRequest.Replace("\"", "\\\"");

                Console.WriteLine(formattedNewsRequest);

                var responseSpecialTitles = await _httpClient.PostAsync("http://gptapi:8080/GPT/GetSpecialTitles", new StringContent($"\"{formattedNewsRequest}\"", Encoding.UTF8, "application/json"));
                if (responseSpecialTitles.IsSuccessStatusCode)
                {

MainApp/MainApp/Controllers/ChatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MainApp.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Npgsql;
using System.Security.Claims;

namespace MainApp.Controllers
{
    public class ChatsController : Controller
    {
        private readonly MyDbContext _context;

        public ChatsController(MyDbContext context)
        {
            _context = context;
            
        }

        // GET: Chats
        [RedirectIfWrongUser]
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Chat");
            }
            else return RedirectToAction("Login", "Account");
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            var dB = _context.Chats.Where(c => c.Username == User.Identity.Name);
            return View(await dB.ToListAsync());
        }

        public async Task<IActionResult> Chats()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            var dB = _context.Chats.Where(c => c.Username == User.Identity.Name);
            return PartialView(new ChatViewModel() { Chats = await dB.ToListAsync()});
        }

        // GET: Chats/Create
        public IActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            return View();
        }

        // POST: Chats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Source,GPT")] Chat chat)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            
            if (ModelState.IsValid)
            {
                _context.Add(chat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Username"] = new SelectList(_context.Users, "Username", "Username");
            return View(chat);
        }

        // GET: Chats/Edit/5
        [RedirectIfWrongUser]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chat = await _context.Chats.FindAsync(id);
            if (chat == null)
            {
                return NotFound();
            }
            ViewData["Username"] = new SelectList(_context.Users, "Username", "Username");
            return View(chat);
        }

        // POST: Chats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RedirectIfWrongUser]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Source,GPT")] Chat chat)
        {
            if (id != chat.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Attach(chat);
                    _context.Entry(chat).State = EntityState.Modified;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChatExists(chat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Username"] = new SelectList(_context.Users, "Username", "Username");
            return View(chat);
        }

        // GET: Chats/Delete/5
        [RedirectIfWrongUser]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chat = await _context.Chats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chat == null)
            {
                return NotFound();
            }

            return View(chat);
        }

        // POST: Chats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [RedirectIfWrongUser]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var chat = await _context.Chats.FindAsync(id);
            if (chat != null)
            {
                _context.Chats.Remove(chat);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChatExists(int id)
        {
            return _context.Chats.Any(e => e.Id == id);
        }
    }
}

MainApp/MainApp/Views/Chats/Chats.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ChatViewModel
@{
    var chats = (Model.Chats, Model.LastTimeMessage);
    for (int i = 0; i < Model.Chats.Count() - 1; i++)
    {
        for (int j = i + 1; j < Model.Chats.Count(); j++)
            if (chats.Item2[j] < chats.Item2[i])
            {
                var temp = (chats.Item1[j], chats.Item2[j]);
                chats.Item1[j] = chats.Item1[i];
                chats.Item2[j] = chats.Item2[i];
                chats.Item1[i] = temp.Item1;
                chats.Item2[i] = temp.Item2;
            }
    }
    DateTime dt = DateTime.Today;
    var datesLabels = new[] { "сегодня", "вчера", "последние 7 дней", "последний месяц", "ранее" };
    var dates = new[] { 0, -1, -7, -30 };
    var groupedDates = new List<List<Chat>>(5) { new List<Chat>(), new List<Chat>(), new List<Chat>(), new List<Chat>(), new List<Chat>() };
    for (int i = 0; i < Model.Chats.Count(); i++)
    {
        if (Model.LastTimeMessage[i] >= dt)
            groupedDates[0].Add(Model.Chats[i]);
        else if (Model.LastTimeMessage[i] >= dt.AddDays(-1))
            groupedDates[1].Add(Model.Chats[i]);
        else if (Model.LastTimeMessage[i] >= dt.AddDays(-7))
            groupedDates[2].Add(Model.Chats[i]);
        else if (Model.LastTimeMessage[i] >= dt.AddDays(-30))
            groupedDates[3].Add(Model.Chats[i]);
        else
            groupedDates[4].Add(Model.Chats[i]);
    }
}
@{
    for(int i = 0; i < groupedDates.Count(); i++)
    {
        if(groupedDates[i].Count > 0)
        {
            <div class="datalabel">@datesLabels[i]</div>
        }
        foreach (var item in groupedDates[i])
        {
            @if (item.Id == Model.ChatId)
            {
                <li class="d-flex justify-content-between align-items-center" style="background-color:darkgray">
                    <a asp-controller="Chat" asp-route-id="@item.Id">
                        @Html.DisplayFor(modelItem => item.Username)
                        @Html.DisplayFor(modelItem => item.Source)
                        @Html.DisplayFor(modelItem => item.GPT)
                        <a asp-controller="Chats" asp-action="Edit" asp-route-id="@item.Id">
                            <button>...</button>
                        </a>
                    </a>
                </li>
            }
            else
            {
                <a asp-controller="Chat" asp-route-id="@item.Id">
                    <li class="d-flex justify-content-between align-items-center">
                        @Html.DisplayFor(modelItem => item.Username)
                        @Html.DisplayFor(modelItem => item.Source)
                        @Html.DisplayFor(modelItem => item.GPT)
                        <a asp-controller="Chats" asp-action="Edit" asp-route-id="@item.Id">
                            <button>...</button>
                        </a>
                    </li>
                </a>
            }
        }
    }
}

MainApp/MainApp/Views/Chats/Create.cshtml
@model MainApp.Models.Chat

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Chat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Username" type="hidden" value="@User.Identity.Name" />
            <div class="form-group">
                <label asp-for="Source" class="control-label"></label>
                <input asp-for="Source" class="form-control" />
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GPT" class="control-label"></label>
                <input asp-for="GPT" class="form-control" />
                <span asp-validation-for="GPT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MainApp/MainApp/Views/Chats/Delete.cshtml
@model MainApp.Models.Chat

@{
    ViewData["Title"] = "Delete";
}

<h1>Удаление</h1>

<h3>Вы уверены, что хотите удалить чат?</h3>
<div>
    <h4>Chat</h4>
    <hr />
    <dl class="row">
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Source)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Source)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GPT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GPT)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Edit" asp-route-id="@Model.Id">>Назад</a>
    </form>
</div>

MainApp/MainApp/Views/Chats/Edit.cshtml
@model MainApp.Models.Chat

@{
    ViewData["Title"] = "Edit";
}

<h1>Настройка чата</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Username" type="hidden" value="@User.Identity.Name" />
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Source" class="control-label"></label>
                <input asp-for="Source" class="form-control" />
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GPT" class="control-label"></label>
                <input asp-for="GPT" class="form-control" />
                <span asp-validation-for="GPT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Chat">Назад</a>
</div>

<div>
    <a asp-action="Delete" asp-route-id="@Model.Id">Удалить чат</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MainApp/MainApp/Views/Chats/Index.cshtml
@model IEnumerable<MainApp.Models.Chat>

@{
    ViewData["Title"] = "";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Source)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GPT)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Source)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GPT)
            </td>
            <td>
                    <a asp-controller="Chat" asp-route-id="@item.Id">Open</a> |
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>